### ISSUE TITLE
Create a wikidata account flagged as a bot

### ISSUE THREAD

**Issue by betson** [CommerceDataService/census-wikidata-bot#1]

**Comment by bahadasx** [comment]
Add entry to Wikidata Bot requests page:
https://www.wikidata.org/wiki/Wikidata:Requests_for_permissions

Go through test round of changes with script and make sure community approves, followed by being granted bot flag status for bot account (CensusBot).

**Comment by bahadasx** [comment]
Followed bot flag request procedure and was granted permissions.  Request and subsequent dialog located at: https://www.wikidata.org/wiki/Wikidata:Requests_for_permissions/Bot/CensusBot

`bot_flag` argument set to `True` in addPopValues.py script as well.
